version: "3.7"

x-environment: &default-environment
  POSTGRES_USER: vscode
  POSTGRES_PASSWORD: notsecure
  POSTGRES_DB: HeinrichHealth

services:
  dev:
    networks:
      - default
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace
    environment:
      <<: *default-environment
    depends_on:
      - db
    command: sleep infinity

  db:
    image: "postgres:12"
    networks:
      - default
    environment:
      - POSTGRES_USER=vscode
      - POSTGRES_PASSWORD=notsecure
      - POSTGRES_DB=HeinrichHealth
      - PGDATA= /var/lib/postgresql/data/some_name
    ports:
      - 5432:5432
    volumes:
      - ./pg-volume:/var/lib/postgresql/data/some_name

networks:
  default:
