FROM ubuntu:20.04 as base 

ARG USERNAME=vscode
ARG USER_UID=1000
ARG USER_GID=$USER_UID

# Ensure apt is in non-interactive to avoid prompts
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update; 
RUN apt-get install -y libc6
RUN apt-get install -y libgcc1
RUN apt-get install -y libgssapi-krb5-2
RUN apt-get install -y libssl1.1
RUN apt-get install -y libstdc++6
RUN apt-get install -y zlib1g

RUN apt-get install -y wget

RUN wget https://packages.microsoft.com/config/ubuntu/21.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
RUN dpkg -i packages-microsoft-prod.deb
RUN rm packages-microsoft-prod.deb

RUN apt-get update; 
RUN apt-get install -y apt-transport-https 
RUN apt-get install -y iputils-ping
RUN apt-get install -y dotnet-sdk-6.0



RUN groupadd --gid $USER_GID $USERNAME \
    && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME

ENV DEBIAN_FRONTEND=dialog

USER $USERNAME