version: "3.7"

x-environment: &default-environment
  POSTGRES_USER: vscode
  POSTGRES_PASSWORD: notsecure
  POSTGRES_DB: heinrich_health

services:
  dev:
    networks:
      - default
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:rw
    environment:
      <<: *default-environment
    user: vscode
    depends_on:
      - db
    command: sleep infinity

  db:
    image: "postgres:12"
    restart: unless-stopped
    networks:
      - default
    environment: *default-environment
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ../postgresql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

volumes:
  pgdata:

networks:
  default:
